# Generated by Django 4.0.4 on 2022-04-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('data', models.DateField(blank=False)),
                ('hora_Inicio', models.TimeField(auto_now_add=False, blank=False)),
                ('hora_Fim', models.TimeField(auto_now_add=False, blank=False)),
                ('local', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=10)),
            ],
        ),
    ]
